# Form implementation generated from reading ui file 'initial_page.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_start_to_adjust(object):
    def setupUi(self, start_to_adjust):
        start_to_adjust.setObjectName("start_to_adjust")
        start_to_adjust.resize(498, 393)
        self.prototype_name = QtWidgets.QLineEdit(parent=start_to_adjust)
        self.prototype_name.setGeometry(QtCore.QRect(110, 50, 271, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(21)
        font.setBold(True)
        self.prototype_name.setFont(font)
        self.prototype_name.setText("")
        self.prototype_name.setObjectName("prototype_name")
        self.prototype_rd_A = QtWidgets.QRadioButton(parent=start_to_adjust)
        self.prototype_rd_A.setGeometry(QtCore.QRect(100, 140, 119, 28))
        self.prototype_rd_A.setObjectName("prototype_rd_A")
        self.prototype_rd_B = QtWidgets.QRadioButton(parent=start_to_adjust)
        self.prototype_rd_B.setGeometry(QtCore.QRect(320, 140, 119, 28))
        self.prototype_rd_B.setObjectName("prototype_rd_B")
        self.start_to_adjust_btn = QtWidgets.QPushButton(parent=start_to_adjust)
        self.start_to_adjust_btn.setGeometry(QtCore.QRect(200, 230, 111, 41))
        self.start_to_adjust_btn.setObjectName("start_to_adjust_btn")

        self.retranslateUi(start_to_adjust)
        QtCore.QMetaObject.connectSlotsByName(start_to_adjust)

    def retranslateUi(self, start_to_adjust):
        _translate = QtCore.QCoreApplication.translate
        start_to_adjust.setWindowTitle(_translate("start_to_adjust", "开始装调"))
        self.prototype_rd_A.setText(_translate("start_to_adjust", "样机A"))
        self.prototype_rd_B.setText(_translate("start_to_adjust", "样机B"))
        self.start_to_adjust_btn.setText(_translate("start_to_adjust", "开始装调"))
